"""add auction lotid

Revision ID: 3185ee63275e
Revises: babe5151fe18
Create Date: 2025-12-17 11:55:08.555486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3185ee63275e'
down_revision: Union[str, Sequence[str], None] = 'babe5151fe18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carfax_purchase', sa.Column('auction', sa.String(), nullable=True))
    op.add_column('carfax_purchase', sa.Column('lot_id', sa.String(), nullable=True))
    op.alter_column('carfax_purchase', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carfax_purchase', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('carfax_purchase', 'lot_id')
    op.drop_column('carfax_purchase', 'auction')
    # ### end Alembic commands ###
