"""init

Revision ID: 86f9a0beaaae
Revises: 
Create Date: 2025-06-24 15:38:35.052692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f9a0beaaae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carfax_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carfax_purchase_source'), 'carfax_purchase', ['source'], unique=False)
    op.create_index(op.f('ix_carfax_purchase_user_external_id'), 'carfax_purchase', ['user_external_id'], unique=False)
    op.create_index(op.f('ix_carfax_purchase_vin'), 'carfax_purchase', ['vin'], unique=False)
    op.create_index('ix_user_source', 'carfax_purchase', ['user_external_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_source', table_name='carfax_purchase')
    op.drop_index(op.f('ix_carfax_purchase_vin'), table_name='carfax_purchase')
    op.drop_index(op.f('ix_carfax_purchase_user_external_id'), table_name='carfax_purchase')
    op.drop_index(op.f('ix_carfax_purchase_source'), table_name='carfax_purchase')
    op.drop_table('carfax_purchase')
    # ### end Alembic commands ###
