"""update carfax

Revision ID: a4daee270ea5
Revises: 86f9a0beaaae
Create Date: 2025-06-24 19:23:22.298669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4daee270ea5'
down_revision: Union[str, Sequence[str], None] = '86f9a0beaaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_search_history_id'), table_name='user_search_history')
    op.drop_table('user_search_history')
    op.drop_index(op.f('ix_find_for_me_id'), table_name='find_for_me')
    op.drop_table('find_for_me')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.alter_column('carfax_purchase', 'vin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

